# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """The inference service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateEncoded = channel.unary_unary(
                '/inference.InferenceService/EvaluateEncoded',
                request_serializer=inference__pb2.EncodedEvalRequest.SerializeToString,
                response_deserializer=inference__pb2.EncodedEvalResponse.FromString,
                _registered_method=True)
        self.EvaluateStream = channel.stream_stream(
                '/inference.InferenceService/EvaluateStream',
                request_serializer=inference__pb2.EncodedEvalRequest.SerializeToString,
                response_deserializer=inference__pb2.EncodedEvalResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """The inference service
    """

    def EvaluateEncoded(self, request, context):
        """Unary RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateStream(self, request_iterator, context):
        """Bidirectional streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateEncoded': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateEncoded,
                    request_deserializer=inference__pb2.EncodedEvalRequest.FromString,
                    response_serializer=inference__pb2.EncodedEvalResponse.SerializeToString,
            ),
            'EvaluateStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EvaluateStream,
                    request_deserializer=inference__pb2.EncodedEvalRequest.FromString,
                    response_serializer=inference__pb2.EncodedEvalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """The inference service
    """

    @staticmethod
    def EvaluateEncoded(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/EvaluateEncoded',
            inference__pb2.EncodedEvalRequest.SerializeToString,
            inference__pb2.EncodedEvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inference.InferenceService/EvaluateStream',
            inference__pb2.EncodedEvalRequest.SerializeToString,
            inference__pb2.EncodedEvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
