# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "inference.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0finference.proto\x12\tinference"\xe4\x01\n\x12\x45ncodedEvalRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x12\x12\n\nrequest_id\x18\x02 \x01(\x05\x12\x14\n\x0cx_data_bytes\x18\n \x01(\x0c\x12\x12\n\nbatch_size\x18\x04 \x01(\x05\x12\x0f\n\x07max_len\x18\x05 \x01(\x05\x12\x1d\n\x15\x65ncoded_lengths_bytes\x18\x0b \x01(\x0c\x12\x18\n\x10legal_mask_bytes\x18\x0c \x01(\x0c\x12\x12\n\nvocab_size\x18\x08 \x01(\x05\x12\x1f\n\x17num_legal_actions_bytes\x18\r \x01(\x0c"\xa9\x01\n\x13\x45ncodedEvalResponse\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x12\x12\n\nrequest_id\x18\x02 \x01(\x05\x12\x1c\n\x14legal_policies_bytes\x18\n \x01(\x0c\x12\x1b\n\x13player_values_bytes\x18\x0b \x01(\x0c\x12\x13\n\x0bnum_players\x18\x05 \x01(\x05\x12\x1b\n\x13total_legal_actions\x18\x06 \x01(\x05\x32\xb9\x01\n\x10InferenceService\x12P\n\x0f\x45valuateEncoded\x12\x1d.inference.EncodedEvalRequest\x1a\x1e.inference.EncodedEvalResponse\x12S\n\x0e\x45valuateStream\x12\x1d.inference.EncodedEvalRequest\x1a\x1e.inference.EncodedEvalResponse(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "inference_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ENCODEDEVALREQUEST"]._serialized_start = 31
    _globals["_ENCODEDEVALREQUEST"]._serialized_end = 259
    _globals["_ENCODEDEVALRESPONSE"]._serialized_start = 262
    _globals["_ENCODEDEVALRESPONSE"]._serialized_end = 431
    _globals["_INFERENCESERVICE"]._serialized_start = 434
    _globals["_INFERENCESERVICE"]._serialized_end = 619
# @@protoc_insertion_point(module_scope)
